# Site settings
title: "D. Andrango | Portafolio digital"
description: "Fisico especializado en Instrumentación científica - Electrónica - Diseño 3D - Programación - Automatización"
author: Damián Andrango
lang: es
baseurl: "/public_portfolio"
url: "https://mdam21.github.io"


# imagen destacada para redes
image: "/public_portfolio/assets/img/avatar.jpeg"

# Include CSS
include:
  - assets

# Build settings
markdown: "kramdown"
permalink: /:categories/:title/

# Custom Chirpy config (optional enhancements)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
nav:
  home: /
  about: /about/
  projects: /projects/
  contact: "mailto:and_damian@outlook.com"

sass:
  style: "compressed"

social:
  name: Damián Andrango
  links:
    - https://github.com/mdam21
    - www.linkedin.com/in/mdamian-andrango
